In [12]:
import numpy as np


In [4]:
#1 Numpy Creation
arr_1d = np.array([1,2,3,4,5])
print("1D array :",arr_1d)


1D array : [1 2 3 4 5]


In [13]:
#2D array
arr_2d = np.array([[1,2,3],[4,5,6]])
print ("2D array:",arr_2d)

2D array: [[1 2 3]
 [4 5 6]]


In [14]:
#List Vs numpy array
py_list=[1,2,3]
print("Multiplication of list:",py_list *2)
array=np.array([1,2,3,4])
print("Multiplication of numpy:",array *2)

Multiplication of list: [1, 2, 3, 1, 2, 3]
Multiplication of numpy: [2 4 6 8]


In [15]:
#Creating array from scratch
zeros= np.zeros((3,4))
print ("zeros array :",zeros)

zeros array : [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
full=np.full((2,3),7)
print ("Full array:",full)

Full array: [[7 7 7]
 [7 7 7]]


In [20]:
#Random value
random=np.random.random((2,3))
print ("Random :",random)

Random : [[0.70661598 0.75463245 0.52155521]
 [0.39042844 0.45267711 0.92467652]]


In [27]:
#vector ,matrics,tensor
vector=np.array([1,2,3])
print("vector:",vector)
matric=np.array([[1,2,3],[4,5,6]])
print ("matric:",matric)
tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print("tensor:",tensor)

vector: [1 2 3]
matric: [[1 2 3]
 [4 5 6]]
tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
# Array properties
arr=np.array([[1,2,3],[4,5,6]])
print("shapes:",arr.shape)
print("Dimension:",arr.ndim)
print("Size:",arr.size)
print("Dtype:",arr.dtype)

shapes: (2, 3)
Dimension: 2
Size: 6
Dtype: int32


In [39]:
#Array reshaping

arr=np.arange(12)
print("Orignal array:",arr)
#reshapedd
reshaped=arr.reshape((3,4))
print("\n Reshaped array",reshaped)
#flattend
flatten= reshaped.flatten()
print("flattend:",flatten)
#ravel (reture view,intead of copy)
raveled=reshaped.ravel()
print("ravel:",raveled)

Orignal array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattend: [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [42]:
#tranpose
transpose=reshaped.T
print("tranpose:",transpose)

tranpose: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [44]:
# numpy array operation
arr=np.array([1,2,3,4,5,6,7,8,9])
print ("Basic slcing :",arr[2:7])
print("With step :",arr[1:8:2])
print ("slicing :",arr[-5])

Basic slcing : [3 4 5 6 7]
With step : [2 4 6 8]
slicing : 5


In [49]:
arr_2d =np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print ("Specific array:",arr_2d[1,2])
print ("all row:",arr_2d[1])
print("all row:",arr_2d[:1])
       

Specific array: 6
all row: [4 5 6]
all row: [[1 2 3]]


In [50]:
#sorting 
unsorted=np.array([3,1,4,1,5,7,3,7,8])
print("sorted array",np.sort(unsorted))

sorted array [1 1 3 3 4 5 7 7 8]


In [55]:
# filterr
number =np.array([1,2,3,4,5,6,7,8,9,10])
even_number =number[number % 2 == 0]
print("Even number:",even_number)

Even number: [ 2  4  6  8 10]


In [57]:
#filter with mask
mask =number > 5
print("number greater than 5:",number[mask])


number greater than 5: [ 6  7  8  9 10]


In [61]:
#fancy indexcing Vs np.where()

indices=[0,2,4]
print(number[indices])
where_result=np.where(number>5)
print(where_result)
print("NP where:",number[where_result])


[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where: [ 6  7  8  9 10]


In [67]:
condition_array=np.where(number>5,"true","false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [75]:
#Adding data
arr1 = np.array([1,2,3])
arr2 = np.array ([5,6,7])
combined = np.concatenate((arr1 ,arr2))
print("Combined:",combined)

Combined: [1 2 3 5 6 7]


In [ ]:
#array compatiblity

In [80]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print("Compatiblity shapes:", a.shape == b.shape)

Compatiblity shapes: True
